/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-01-24 07:47:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.back_002dend.Location;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.location.model.LocationVO;
import com.location.model.LocationService;
import java.util.List;
import com.location.model.LocationVO;

public final class getAllLoc_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/Users/Tibame_T14/Documents/myproject/apache-tomcat-9.0.70/webapps/CGA105G7/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1064305020000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1673314490106L));
    _jspx_dependants.put("/back-end/Location/page2.file", Long.valueOf(1674542227443L));
    _jspx_dependants.put("/back-end/Location/updateLoc.jsp", Long.valueOf(1674317661149L));
    _jspx_dependants.put("/back-end/Location/page1.file", Long.valueOf(1674541306509L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.location.model.LocationVO");
    _jspx_imports_classes.add("com.location.model.LocationService");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems_005fend_005fbegin;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems_005fend_005fbegin.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

LocationService locSvc = new LocationService();
List<LocationVO> list = locSvc.getAll();
pageContext.setAttribute("list", list);

      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
  int rowsPerPage = 5;  //每頁的筆數    
    int rowNumber=0;      //總筆數
    int pageNumber=0;     //總頁數      
    int whichPage=1;      //第幾頁
    int pageIndexArray[]=null;
    int pageIndex=0; 

      out.write("\r\n");
      out.write("\r\n");
  
    rowNumber=list.size();
    if (rowNumber%rowsPerPage !=0)
         pageNumber=rowNumber/rowsPerPage + 1;
    else pageNumber=rowNumber/rowsPerPage;    

    pageIndexArray=new int[pageNumber]; 
    for (int i=1 ; i<=pageIndexArray.length ; i++)
         pageIndexArray[i-1]=i*rowsPerPage-rowsPerPage;

      out.write("\r\n");
      out.write("\r\n");
  try {
       whichPage = Integer.parseInt(request.getParameter("whichPage"));
       pageIndex=pageIndexArray[whichPage-1];
    } catch (NumberFormatException e) { //第一次執行的時候
       whichPage=1;
       pageIndex=0;
    } catch (ArrayIndexOutOfBoundsException e) { //總頁數之外的錯誤頁數
         if (pageNumber>0){
              whichPage=pageNumber;
              pageIndex=pageIndexArray[pageNumber-1];
         }
    } 

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table class=\"table\" id=\"loctable\">\r\n");
      out.write("	<thead>\r\n");
      out.write("		<tr>\r\n");
      out.write("			<th scope=\"col\">編號</th>\r\n");
      out.write("			<th scope=\"col\">景點名稱</th>\r\n");
      out.write("			<th scope=\"col\">地址</th>\r\n");
      out.write("			<th scope=\"col\">聯絡電話</th>\r\n");
      out.write("			<th scope=\"col\">景點狀態</th>\r\n");
      out.write("			<th scope=\"col\">圖片</th>\r\n");
      out.write("			<th scope=\"col\">編輯</th>\r\n");
      out.write("\r\n");
      out.write("		</tr>\r\n");
      out.write("	</thead>\r\n");
      out.write("	<tbody>\r\n");
      out.write("		");
 int i = (whichPage-1)*rowsPerPage; 
      out.write("\r\n");
      out.write("		");
      //  c:forEach
      org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
      boolean _jspx_th_c_005fforEach_005f0_reused = false;
      try {
        _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fforEach_005f0.setParent(null);
        // /back-end/Location/getAllLoc.jsp(28,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setVar("locVO");
        // /back-end/Location/getAllLoc.jsp(28,2) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        // /back-end/Location/getAllLoc.jsp(28,2) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setBegin(pageIndex);
        // /back-end/Location/getAllLoc.jsp(28,2) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fforEach_005f0.setEnd(pageIndex+rowsPerPage-1);
        int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
        try {
          int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
          if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("\r\n");
              out.write("			<tr class=\"align-middle\">\r\n");
              out.write("				");
 i++; 
              out.write("\r\n");
              out.write("				<td>");
              out.print(i );
              out.write("</td>\r\n");
              out.write("				<td>");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${locVO.locName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("</td>\r\n");
              out.write("				<td>");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${locVO.locAddress}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("</td>\r\n");
              out.write("				<td>");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${locVO.locPhone == null? \"查無資料\" : locVO.locPhone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("</td>\r\n");
              out.write("				<td>");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${locVO.locStatus == 0? \"上架\" : \"未上架\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("</td>\r\n");
              out.write("				<td>\r\n");
              out.write("\r\n");
              out.write("						<input type=\"hidden\" name=\"action\" value=\"getOne_For_Update\">\r\n");
              out.write("						<input type=\"hidden\" name=\"LOC_ID\" value=\"");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${locVO.getLocId()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("\">\r\n");
              out.write("\r\n");
              out.write("\r\n");
              out.write("						<button class=\"btn btn-primary py-1 px-2\" data-bs-toggle=\"modal\"\r\n");
              out.write("							data-bs-target=\"#updatePic\">預覽編輯圖片</button>\r\n");
              out.write("				</td>\r\n");
              out.write("				<td>\r\n");
              out.write("\r\n");
              out.write("							<a href=\"loc.do?LOC_ID=");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${locVO.locId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("&action=getOne_For_Update\" class=\"btn btn-primary py-1 px-2\">編輯</a>\r\n");
              out.write("				</td>\r\n");
              out.write("			</tr>\r\n");
              out.write("		");
              int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            return;
          }
        } catch (java.lang.Throwable _jspx_exception) {
          while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
            out = _jspx_page_context.popBody();
          _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
        } finally {
          _jspx_th_c_005fforEach_005f0.doFinally();
        }
        _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f0);
        _jspx_th_c_005fforEach_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
      }
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</tbody>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("	  <!-- 編輯 modal content start -->\r\n");
      out.write("	  ");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f0_reused = false;
      try {
        _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f0.setParent(null);
        // /back-end/Location/getAllLoc.jsp(56,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ openModal != null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
        int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
        if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("      ");
            out.write("\r\n");
            out.write("\r\n");
            out.write("	\r\n");
LocationVO locVO = (LocationVO)request.getAttribute("locVO"); 
            out.write("\r\n");
            out.write("	\r\n");
            out.write("	\r\n");
            out.write("    \r\n");
            out.write("    <div class=\"modal fade\" id=\"update\">\r\n");
            out.write("        <div class=\"modal-dialog\">\r\n");
            out.write("\r\n");
            out.write("          <form action=\"loc.do\" class=\"modal-content\" method=\"post\">\r\n");
            out.write("            <div class=\"modal-header\">\r\n");
            out.write("              <h5 class=\"modal-title fw-bold\" id=\"updateLoc\">編輯景點</h5>\r\n");
            out.write("              <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
            out.write("            </div>\r\n");
            out.write("            \r\n");
            out.write("            <div class=\"modal-body\">\r\n");
            out.write("              <div class=\"container\">\r\n");
            out.write("                <div class=\"row m-2\">\r\n");
            out.write("                  <div class=\"col text-end p-0\">\r\n");
            out.write("                    <label for=\"Uloc_name\">景點名稱 : </label>\r\n");
            out.write("                  </div>\r\n");
            out.write("                  <div class=\"col\">\r\n");
            out.write("                    <input type=\"text\" name=\"loc_name\" id=\"Uloc_name\" maxlength=\"15\" placeholder=\"必填\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${locVO.locName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                  </div>\r\n");
            out.write("                  <div class=\"col text-start p-0\">\r\n");
            out.write("                    <span id=\"Uloc-error\"></span>\r\n");
            out.write("                  </div>\r\n");
            out.write("                </div>\r\n");
            out.write("\r\n");
            out.write("                <div class=\"row m-2\">\r\n");
            out.write("                  <div class=\"col text-end p-0\">\r\n");
            out.write("                    <label for=\"Ulongitude\">經度 : </label>\r\n");
            out.write("                  </div>\r\n");
            out.write("                  <div class=\"col\">\r\n");
            out.write("                    <input type=\"text\" name=\"longitude\" id=\"Ulongitude\" maxlength=\"30\" placeholder=\"必填\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${locVO.longitude}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                  </div>\r\n");
            out.write("                  <div class=\"col text-start p-0\">\r\n");
            out.write("                    <span id=\"Ulong-error\"></span>\r\n");
            out.write("                  </div>\r\n");
            out.write("                </div>\r\n");
            out.write("\r\n");
            out.write("                <div class=\"row m-2\">\r\n");
            out.write("                  <div class=\"col text-end p-0\">\r\n");
            out.write("                    <label for=\"Ulatitude\">緯度 : </label>\r\n");
            out.write("                  </div>\r\n");
            out.write("                  <div class=\"col\">\r\n");
            out.write("                    <input type=\"text\" name=\"latitude\" id=\"Ulatitude\" maxlength=\"30\" placeholder=\"必填\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${locVO.latitude}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                  </div>\r\n");
            out.write("                  <div class=\"col text-start p-0\">\r\n");
            out.write("                    <span id=\"Ulati-error\"></span>\r\n");
            out.write("                  </div>\r\n");
            out.write("                </div>\r\n");
            out.write("\r\n");
            out.write("                <div class=\"row m-2\">\r\n");
            out.write("                  <div class=\"col text-end p-0\">\r\n");
            out.write("                    <label for=\"Uaddress\">地址 : </label>\r\n");
            out.write("                  </div>\r\n");
            out.write("                  <div class=\"col\">\r\n");
            out.write("                    <input type=\"text\" name=\"address\" id=\"Uaddress\" maxlength=\"30\" placeholder=\"必填\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${locVO.locAddress}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                  </div>\r\n");
            out.write("                  <div class=\"col text-start p-0\">\r\n");
            out.write("                    <span id=\"Uaddress-error\"></span>\r\n");
            out.write("                  </div>\r\n");
            out.write("                </div>\r\n");
            out.write("\r\n");
            out.write("                <div class=\"row m-2\">\r\n");
            out.write("                  <div class=\"col text-end p-0\">\r\n");
            out.write("                    <label for=\"Uphone\">連絡電話 : </label>\r\n");
            out.write("                  </div>\r\n");
            out.write("                  <div class=\"col\">\r\n");
            out.write("                    <input type=\"text\" name=\"phone\" id=\"Uphone\" maxlength=\"15\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${locVO.locPhone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                  </div>\r\n");
            out.write("                  <div class=\"col text-start p-0\">\r\n");
            out.write("                    <span id=\"Uphone-error\"></span>\r\n");
            out.write("                  </div>\r\n");
            out.write("                </div>\r\n");
            out.write("\r\n");
            out.write("                <div class=\"row m-2\">\r\n");
            out.write("                  <div class=\"col text-center p-0\">\r\n");
            out.write("                    <div>景點狀態 : </div>\r\n");
            out.write("                  </div>\r\n");
            out.write("                  <div class=\"col-3 text-start\">							\r\n");
            out.write("                   <input type=\"radio\" name=\"state\" id=\"puton\" value=\"0\" ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${locVO.locStatus == 0? \"checked\" : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" > \r\n");
            out.write("                   <label for=\"puton\">上架</label>		\r\n");
            out.write("                  </div>\r\n");
            out.write("                  <div class=\"col text-start\">\r\n");
            out.write("                    <input type=\"radio\" name=\"state\" id=\"putoff\" value=\"1\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${locVO.locStatus == 1? \"checked\" : \"\"}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" > \r\n");
            out.write("                    <label for=\"putoff\">下架</label>	\r\n");
            out.write("                  </div>\r\n");
            out.write("                </div>\r\n");
            out.write("              </div>\r\n");
            out.write("\r\n");
            out.write("            </div>\r\n");
            out.write("            <div class=\"modal-footer\">\r\n");
            out.write("            \r\n");
            out.write("            <input type=\"hidden\" name=\"action\" value=\"update\">\r\n");
            out.write("            <input type=\"hidden\" name=\"locId\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${locVO.locId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("			<input type=\"hidden\" name=\"userId\" value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${locVO.userId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("			\r\n");
            out.write("              <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">取消</button>\r\n");
            out.write("              <button type=\"submit\" class=\"btn btn-primary\" id=\"updateSend\" disabled>送出</button>\r\n");
            out.write("            </div>\r\n");
            out.write("          </form>\r\n");
            out.write("\r\n");
            out.write("        </div>\r\n");
            out.write("      </div>\r\n");
            out.write(" 		<script>\r\n");
            out.write("      $(document).ready(function(){\r\n");
            out.write("    	  $('#update').modal('show');\r\n");
            out.write("    	});\r\n");
            out.write("      </script>\r\n");
            out.write("      ");
            out.write("\r\n");
            out.write("      <!-- 編輯 modal content end -->\r\n");
            out.write("	  ");
            int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
        _jspx_th_c_005fif_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
      }
      out.write(' ');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("<p class=\"col text-start\">總資料筆數: 共<font color=red>");
      out.print(rowNumber);
      out.write("</font>筆</p>\r\n");
      out.write("\r\n");
      out.write("  <nav class=\"col-auto\">\r\n");
      out.write("  <ul class=\"pagination\">\r\n");
      out.write("  ");
 String firstPage="disabled";
  if(pageIndex>=rowsPerPage){
  	firstPage="";
  }
      out.write("  \r\n");
      out.write("    <li class=\"page-item ");
      out.print(firstPage);
      out.write("\">\r\n");
      out.write("      <a class=\"page-link\" href=\"");
      out.print(request.getRequestURI());
      out.write("?whichPage=1\">&laquo;</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    \r\n");
      out.write("    ");
if(whichPage != 1){
      out.write(" <!-- 檢查如果是第一頁則不用顯示 -->\r\n");
      out.write("     <li class=\"page-item\">\r\n");
      out.write("    	<a class=\"page-link\" href=\"");
      out.print(request.getRequestURI());
      out.write("?whichPage=");
      out.print(whichPage-1);
      out.write('"');
      out.write('>');
      out.print(whichPage-1);
      out.write("</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    ");
}
      out.write("\r\n");
      out.write("    \r\n");
      out.write("  ");
if (pageNumber>0){
      out.write("<!-- 顯示當前的頁數 -->\r\n");
      out.write("    <li class=\"page-item active\">\r\n");
      out.write("    	<a class=\"page-link\">");
      out.print(whichPage);
      out.write("</a>\r\n");
      out.write("    </li>\r\n");
      out.write("  ");
}
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    ");
if(whichPage != pageNumber){
      out.write(" <!-- 檢查如果是最後一頁，則不用顯示 -->\r\n");
      out.write("     \r\n");
      out.write("     <li class=\"page-item\">\r\n");
      out.write("    	<a class=\"page-link\" href=\"");
      out.print(request.getRequestURI());
      out.write("?whichPage=");
      out.print(whichPage+1);
      out.write('"');
      out.write('>');
      out.print(whichPage+1);
      out.write("</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    ");
}
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    ");
 String lastPage ="disabled";
    if(pageIndex<pageIndexArray[pageNumber-1]){
    	lastPage = "";
    }
      out.write("\r\n");
      out.write("    <li class=\"page-item ");
      out.print(lastPage);
      out.write("\">\r\n");
      out.write("      <a class=\"page-link\" href=\"");
      out.print(request.getRequestURI());
      out.write("?whichPage=");
      out.print(pageNumber);
      out.write("\">&raquo;</a>\r\n");
      out.write("    </li>\r\n");
      out.write("  </ul>\r\n");
      out.write("</nav>\r\n");
      out.write("</div>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
