/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-01-26 17:48:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.front_002dend.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/Tibame_T14/Documents/myproject/apache-tomcat-9.0.70/webapps/CGA105G7_front/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1064305020000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1674754930023L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>7Tour Login </title>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-1.10.2.min.js\"></script>\r\n");
      out.write("    <link href=\"https://netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <script src=\"https://netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container bootstrap snippets bootdey\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-sm-6 col-md-4 col-md-offset-4\">\r\n");
      out.write("                <h1 class=\"text-center login-title\">想尋找更多嗎? <a href=\"");
      out.print(request.getContextPath());
      out.write("/front-end/index.jsp\"\r\n");
      out.write("                        target=\"__blank\">7Tour</a></h1>\r\n");
      out.write("                <div class=\"account-wall\">\r\n");
      out.write("                    <img class=\"profile-img\" src=\"");
      out.print(request.getContextPath());
      out.write("/front-end/member/images/Tour(circle).jpg\" alt=\"\">\r\n");
      out.write("                    <form class=\"form-signin\"  METHOD=\"post\" ACTION=\"");
      out.print(request.getContextPath());
      out.write("/usersServlet\">\r\n");
      out.write("                    	<input type=\"text\" class=\"form-control\" placeholder=\"請輸入電子信箱\" required autofocus name=\"userAccount\">\r\n");
      out.write("                        <input type=\"password\" class=\"form-control\" placeholder=\"請輸入密碼\" required name=\"password\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"action\" value=\"login\">\r\n");
      out.write("                        <button class=\"btn btn-lg btn-primary btn-block\" type=\"submit\">\r\n");
      out.write("                            Sign in</button>\r\n");
      out.write("                        <label class=\"checkbox pull-left\">\r\n");
      out.write("                            <input type=\"checkbox\" value=\"remember-me\">\r\n");
      out.write("                            Remember me\r\n");
      out.write("                        </label>\r\n");
      out.write("                        <a href=\"");
      out.print(request.getContextPath());
      out.write("/front-end/member/addMember.jsp\" class=\"pull-right need-help\">還不是會員嗎? 立即註冊 7Tour 帳號 </a><span class=\"clearfix\"></span>\r\n");
      out.write("                    </form>\r\n");
      out.write("                </div>\r\n");
      out.write("                <a href=\"#\" class=\"text-center new-account\">忘記密碼? </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("        body {\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("            background: #ddd;\r\n");
      out.write("            background-image: url(");
      out.print(request.getContextPath());
      out.write("/front-end/member/images/login.jpeg);\r\n");
      out.write("            background-size: 100%;\r\n");
      out.write("            background-repeat: no-repeat;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body .text-center>a {\r\n");
      out.write("            font-size: 48px;\r\n");
      out.write("            color: purple;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body .text-center>a:hover {\r\n");
      out.write("            color: rgba(236, 126, 9, 0.945);\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-signin {\r\n");
      out.write("            max-width: 330px;\r\n");
      out.write("            padding: 15px;\r\n");
      out.write("            margin: 0 auto;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("         .form-signin .form-signin-heading, \r\n");
      out.write("         .form-signin .checkbox { \r\n");
      out.write("             margin-bottom: 10px; \r\n");
      out.write("\r\n");
      out.write("        } \r\n");
      out.write("\r\n");
      out.write("         .form-signin .checkbox { \r\n");
      out.write("            font-weight: normal; \r\n");
      out.write("\r\n");
      out.write("        } \r\n");
      out.write("\r\n");
      out.write("        .form-signin .form-control {\r\n");
      out.write("            position: relative;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("            height: auto;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            -webkit-box-sizing: border-box;\r\n");
      out.write("            -moz-box-sizing: border-box;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-signin .form-control:focus {\r\n");
      out.write("            z-index: 2;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-signin input[type=\"text\"] {\r\n");
      out.write("            margin-bottom: -1px;\r\n");
      out.write("            border-bottom-left-radius: 0;\r\n");
      out.write("            border-bottom-right-radius: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-signin input[type=\"password\"] {\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("            border-top-left-radius: 0;\r\n");
      out.write("            border-top-right-radius: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .account-wall {\r\n");
      out.write("            /* 登入邊框 */\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("            padding: 40px 0px 20px 0px;\r\n");
      out.write("            background-color: #f7f7f7;\r\n");
      out.write("            -moz-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);\r\n");
      out.write("            -webkit-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);\r\n");
      out.write("            box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .login-title {\r\n");
      out.write("            color: #555;\r\n");
      out.write("            font-size: 18px;\r\n");
      out.write("            font-weight: 400;\r\n");
      out.write("            display: block;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .profile-img {\r\n");
      out.write("            width: 96px;\r\n");
      out.write("            height: 96px;\r\n");
      out.write("            margin: 0 auto 10px;\r\n");
      out.write("            display: block;\r\n");
      out.write("            -moz-border-radius: 50%;\r\n");
      out.write("            -webkit-border-radius: 50%;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .need-help {\r\n");
      out.write("            margin:15px 40px  0px 0px;\r\n");
      out.write("            \r\n");
      out.write("            color:#0CE9EB;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .new-account {\r\n");
      out.write("            display: block;\r\n");
      out.write("            margin-top: 10px;\r\n");
      out.write("            color:#25DB8C;\r\n");
      out.write("            \r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
