/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2023-01-30 15:44:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.front_002dend.TripPlan;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.location.model.LocationVO;
import com.location.model.LocationService;
import com.locationPic.model.LocationPicService;
import com.locationPic.model.LocationPicVO;
import java.util.List;
import com.tripDetail.model.TripDetailService;
import com.tripDetail.model.TripDetailVO;
import java.sql.Date;
import java.util.Calendar;
import java.text.SimpleDateFormat;
import java.util.Base64;
import com.trip.model.TripService;
import com.trip.model.TripVO;
import com.location.model.LocationService;
import com.locationPic.model.LocationPicService;
import com.location.model.LocationVO;
import java.util.List;
import java.util.Base64;

public final class tripPlan_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;
private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_1;
private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_2;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction(null, null, null, null);
  _jspx_fnmap_1= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction(null, null, null, null);
  _jspx_fnmap_2= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction(null, null, null, null);
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/front-end/TripPlan/../headAndFoot/header.jsp", Long.valueOf(1674923539817L));
    _jspx_dependants.put("jar:file:/C:/Users/Tibame_T14/Documents/myproject/apache-tomcat-9.0.70/webapps/CGA105G7/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1064305020000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1673314490106L));
    _jspx_dependants.put("/front-end/TripPlan/getOne_LocInfo.jsp", Long.valueOf(1675093452974L));
    _jspx_dependants.put("/front-end/TripPlan/../headAndFoot/footer.jsp", Long.valueOf(1674918368832L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.trip.model.TripVO");
    _jspx_imports_classes.add("com.location.model.LocationVO");
    _jspx_imports_classes.add("com.locationPic.model.LocationPicVO");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("com.location.model.LocationService");
    _jspx_imports_classes.add("com.tripDetail.model.TripDetailVO");
    _jspx_imports_classes.add("java.sql.Date");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Base64");
    _jspx_imports_classes.add("java.util.Calendar");
    _jspx_imports_classes.add("com.locationPic.model.LocationPicService");
    _jspx_imports_classes.add("com.tripDetail.model.TripDetailService");
    _jspx_imports_classes.add("com.trip.model.TripService");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

//先接userId UsersVO usersVO = (UsersVO) session.getAttribute("usersVO");
	Integer userId = 1;//這邊先將userId寫死
	
// 	String tripId = request.getParameter("TRIP_ID");
	Integer tripId = 2;
	TripService tripSvc = new TripService();
	TripVO tripVO = tripSvc.getOneTrip(tripId);
	pageContext.setAttribute("tripVO", tripVO);
	
// tripDetail take info
	TripDetailService tripDetailSvc = new TripDetailService();
	List<TripDetailVO> list = tripDetailSvc.getTrip_TripDetail(tripId);
	pageContext.setAttribute("list", list);
	
// get location info
	LocationVO locVO = (LocationVO)request.getAttribute("locVO");
//get location Pic
	if(locVO != null){
		LocationPicService locPicSvc = new LocationPicService();
		List<LocationPicVO> locPicList = locPicSvc.getLocPic(locVO.getLocId());
		pageContext.setAttribute("locPicList", locPicList);		
		}

      out.write("\r\n");
      out.write("\r\n");
      out.write("  ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css\" rel=\"stylesheet\"\r\n");
      out.write("    integrity=\"sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU\" crossorigin=\"anonymous\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css\"\r\n");
      out.write("    integrity=\"sha384-b6lVK+yci+bfDmaY1u0zE8YYJt0TZxLEAFyYSLHId4xoVvsrQu3INevFKo+Xir8e\" crossorigin=\"anonymous\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/front-end/css/jquery.datetimepicker.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/front-end/css/header.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/front-end/css/userTripAll.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/front-end/css/tripPlan.css\">\r\n");
      out.write("   <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.3/jquery.min.js\"\r\n");
      out.write("    integrity=\"sha512-STof4xm1wgkfm7heWqFJVn58Hm3EtS31XFaagaa8VMReCXAkQnJZ+jEy8PCC/iT18dFy95WcExNHFTqLyp72eQ==\"\r\n");
      out.write("    crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\"></script>\r\n");
      out.write("    \r\n");
      out.write("<!-- below is tripPlan  -->\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://unpkg.com/leaflet@1.9.3/dist/leaflet.css\"\r\n");
      out.write("    integrity=\"sha256-kLaT2GOSpHechhsozzB+flnD+zUyjE2LlfWPgU04xyI=\" crossorigin=\"\" />\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body style=\"overflow: auto\">\r\n");
      out.write("  <!-- nav start -->\r\n");
      out.write("  <nav class=\"navbar navbar-expand-lg navbar-light bg-cblue sticky-top\">\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("      <a class=\"navbar-brand\" href=\"./header.html\">\r\n");
      out.write("        <img src=\"");
      out.print(request.getContextPath() );
      out.write("/front-end/images/Logo.jpg\" id=\"logo\">\r\n");
      out.write("      </a>\r\n");
      out.write("      <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\"\r\n");
      out.write("        aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("        <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("      </button>\r\n");
      out.write("      <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("        <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("          <li class=\"nav-item hover-down\">\r\n");
      out.write("            <a class=\"nav-link fs-5 fw-bold\" href=\"#\">論壇</a>\r\n");
      out.write("            <ul class=\"bg-cblue hover-list\">\r\n");
      out.write("              <li><a class=\"hover-item fs-5 fw-bold\" href=\"#\">論壇首頁</a></li>\r\n");
      out.write("              <li><a class=\"hover-item fs-5 fw-bold\" href=\"#\">文章</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item hover-down\">\r\n");
      out.write("            <a class=\"nav-link fs-5 fw-bold\" href=\"#\">訂房</a>\r\n");
      out.write("            <ul class=\"bg-cblue hover-list\">\r\n");
      out.write("              <li><a class=\"hover-item fs-5 fw-bold\" href=\"#\">訂房首頁</a></li>\r\n");
      out.write("              <li><a class=\"hover-item fs-5 fw-bold\" href=\"#\">我的訂單</a></li>\r\n");
      out.write("              <li><a class=\"hover-item fs-5 fw-bold\" href=\"#\">購物車</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li class=\"nav-item hover-down\">\r\n");
      out.write("            <a class=\"nav-link fs-5 fw-bold\" href=\"#\">揪團</a>\r\n");
      out.write("            <ul class=\"bg-cblue hover-list\">\r\n");
      out.write("              <li><a class=\"hover-item fs-5 fw-bold\" href=\"#\">揪團首頁</a></li>\r\n");
      out.write("              <li><a class=\"hover-item fs-5 fw-bold\" href=\"#\">建立揪團</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <ul class=\"navbar-nav mb-2 mb-lg-0\">\r\n");
      out.write("          <li class=\"nav-item bg-dblue rounded mx-3 input-group\">\r\n");
      out.write("            <input type=\"search\" class=\"form-control\">\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-primary\">\r\n");
      out.write("              <i class=\"fas fa-search\"></i>\r\n");
      out.write("            </button>\r\n");
      out.write("          </li>\r\n");
      out.write("\r\n");
      out.write("          <li class=\"nav-item user-msg\">\r\n");
      out.write("            <i class=\"bi bi-bell-fill fa-2x msg-icon\"></i>\r\n");
      out.write("            <ul class=\"bg-cblue msg-list\">\r\n");
      out.write("              <li class=\"msg-item\">\r\n");
      out.write("                <h5>title</h5>\r\n");
      out.write("                <p class=\"text-truncate\">\r\n");
      out.write("                  訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容訊息內容\r\n");
      out.write("                </p>\r\n");
      out.write("              </li>\r\n");
      out.write("              <hr class=\"m-1\">\r\n");
      out.write("\r\n");
      out.write("              <li class=\"msg-item\">\r\n");
      out.write("                <h5>title</h5>\r\n");
      out.write("                <p class=\"text-truncate\">訊息內容</p>\r\n");
      out.write("              </li>\r\n");
      out.write("              <hr class=\"m-1\">\r\n");
      out.write("\r\n");
      out.write("              <li class=\"msg-item\">\r\n");
      out.write("                <form action=\"\">\r\n");
      out.write("                  <h5>XXX邀請你，共同規畫行程</h5>\r\n");
      out.write("                  <button class=\"btn btn-primary rounded p-1\">確認</button>\r\n");
      out.write("                  <button class=\"btn btn-danger rounded p-1\">拒絕</button>\r\n");
      out.write("                </form>\r\n");
      out.write("              </li>\r\n");
      out.write("              <hr class=\"m-1\">\r\n");
      out.write("\r\n");
      out.write("              <li class=\"msg-item\">\r\n");
      out.write("                <h5>title</h5>\r\n");
      out.write("                <p class=\"text-truncate\">訊息內容</p>\r\n");
      out.write("              </li>\r\n");
      out.write("              <hr class=\"m-1\">\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("\r\n");
      out.write("          <li class=\"nav-item mx-3 user-info\">\r\n");
      out.write("            <img src=\"");
      out.print(request.getContextPath() );
      out.write("/front-end/images/dog.jpeg\" alt=\"會員照片\" class=\"user-pic\">\r\n");
      out.write("            <ul class=\"bg-cblue info-list\">\r\n");
      out.write("              <li><a href=\"#\" class=\"d-block info-item\">會員基本資料</a></li>\r\n");
      out.write("              <li><a href=\"#\" class=\"d-block info-item\">我的行程</a></li>\r\n");
      out.write("              <li><a href=\"#\" class=\"d-block info-item\">我的收藏</a></li>\r\n");
      out.write("              <li><a href=\"#\" class=\"d-block info-item\">我的訂單</a></li>\r\n");
      out.write("              <li><a href=\"#\" class=\"d-block info-item\">登出</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>\r\n");
      out.write("  <!-- nav end -->");
      out.write("\r\n");
      out.write("    <title>7 Tour | 行程規劃 | TripPlan</title>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("  <div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("      <!-- right start -->\r\n");
      out.write("      <div class=\"col-3 overflow-auto scroll-style\" style=\"height: calc(100vh - 66px);\">\r\n");
      out.write("        <div class=\"row align-items-center p-0\" style=\"background-color: rgba(38, 112, 180, 0.2); height: 10%;\">\r\n");
      out.write("          <div class=\"col-2\">\r\n");
      out.write("            <button class=\"btn\"><i class=\"bi bi-arrow-left\"></i></button>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-5\">\r\n");
      out.write("            <p class=\"m-0 text-truncate\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tripVO.tripName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-5 p-0\">\r\n");
      out.write("            <button class=\"btn trip-btn offset-md-3\" id=\"custom-Loc\">自訂景點</button>\r\n");
      out.write("            <!-- href=\"#loc-info\" data-bs-toggle=\"collapse\"-->\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <div class=\"col p-0\" style=\"height: 150px\">\r\n");
      out.write("          ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("          ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            <div class=\"trip-time fw-bold input-group align-items-center\">\r\n");
      out.write("              <input class=\"form-control trip-in\" type=\"text\">\r\n");
      out.write("              <span><i class=\"bi bi-arrow-right-circle-fill fa-2x cblue\"></i></span>\r\n");
      out.write("              <input class=\"form-control trip-in\" type=\"text\">\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <button class=\"col date-btn\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SimpleDateFormat(\"MM/dd\").format(tripVO.startDate)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("</button>\r\n");
      out.write("          ");
for (Date date = tripVO.getStartDate(); !date.equals(tripVO.getEndDate());){
              Calendar cal = Calendar.getInstance();
              cal.setTime(date);
              cal.add(Calendar.DAY_OF_MONTH,1);
              date = new Date(cal.getTime().getTime());
           
      out.write("\r\n");
      out.write("          	<button class=\"col date-btn\">");
      out.print(new SimpleDateFormat("MM/dd").format(date));
      out.write("</button>\r\n");
      out.write("          	");
}
      out.write("\r\n");
      out.write("          \r\n");
      out.write("          <button class=\"col date-btn\"><i class=\"bi bi-arrow-right\"></i></button>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row \">\r\n");
      out.write("          <p class=\"col-6 px-3 py-2 m-0\">第一天:");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SimpleDateFormat(\"MM/dd\").format(tripVO.startDate)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
      out.write("</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("	");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- right end -->\r\n");
      out.write("\r\n");
      out.write("      <!-- loc info start -->\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

//先接userId UsersVO usersVO = (UsersVO) session.getAttribute("usersVO");
	
//先去userId去找出 該user的自訂景點
	LocationService locSvc = new LocationService();
	List<LocationVO> loclist = locSvc.getForUserId(userId);
	pageContext.setAttribute("loclist", loclist);

      out.write("\r\n");
      out.write("   \r\n");
      out.write("     <div class=\"col-3 locInfo-title collapse\" id=\"loc-info\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <ul class=\"nav nav-pills p-0\" id=\"pills-tab\" role=\"tablist\">\r\n");
      out.write("            <li class=\"nav-item col-5\" role=\"presentation\">\r\n");
      out.write("              <button class=\"btn trip-btn w-100 active\" id=\"locInfo-tab\">\r\n");
      out.write("                <i class=\"bi bi-geo-alt-fill fa-2x\"></i>\r\n");
      out.write("                <p class=\"m-0 d-inline\">地點</p>\r\n");
      out.write("              </button>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item col-5\" role=\"presentation\">\r\n");
      out.write("              <button class=\"btn trip-btn w-100\" id=\"cusLoc-tab\" data-bs-toggle=\"pill\" data-bs-target=\"#cusLoc\"\r\n");
      out.write("                type=\"button\" role=\"tab\" aria-controls=\"cusLoc\" aria-selected=\"false\">\r\n");
      out.write("                <i class=\"bi bi-pencil-fill fa-2x\"></i>\r\n");
      out.write("                <p class=\"m-0 d-inline\">自訂地點</p>\r\n");
      out.write("              </button>\r\n");
      out.write("            </li>\r\n");
      out.write("             <li class=\"nav-item col-2\" role=\"presentation\">\r\n");
      out.write("              <button class=\"btn trip-btn w-100 h-100\" id=\"cusLoc-tab\" data-bs-toggle=\"pill\" data-bs-target=\"#cusLoc\"\r\n");
      out.write("                type=\"button\" role=\"tab\" aria-controls=\"cusLoc\" aria-selected=\"false\" onclick=\"closeLocInfo()\">\r\n");
      out.write("                <i class=\"bi bi-x-lg\"></i>\r\n");
      out.write("              </button>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"tab-content h-100 p-0\" id=\"pills-tabContent\">\r\n");
      out.write("          \r\n");
      out.write("          <!-- loc info start -->\r\n");
      out.write("         ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("            <!-- loc info end -->\r\n");
      out.write("\r\n");
      out.write("            <!-- custom location start -->\r\n");
      out.write("            <div class=\"tab-pane fade container  overflow-auto\" style=\"height: calc(100vh - 66px - 65px);\" id=\"cusLoc\"\r\n");
      out.write("              role=\"tabpanel\" aria-labelledby=\"cusLoc-tab\">\r\n");
      out.write("              <form action=\"#\" method=\"post\" class=\"row\">\r\n");
      out.write("                <h3 class=\"fw-bold p-0 mt-3\">建立新景點</h3>\r\n");
      out.write("                <p class=\"text-danger\">* 星號為必填欄位</p>\r\n");
      out.write("                <input type=\"text\" class=\"col-12 newLoc-input\" placeholder=\"*請輸入地點名稱\">\r\n");
      out.write("                <input type=\"text\" class=\"col-12 newLoc-input\" placeholder=\"*請輸入地址\">\r\n");
      out.write("                <input type=\"text\" class=\"col-12 newLoc-input\" placeholder=\"請輸入電話\">\r\n");
      out.write("                <button class=\"btn trip-btn mt-3 border-dark\">建立</button>\r\n");
      out.write("              </form>\r\n");
      out.write("              <!-- custom location end -->\r\n");
      out.write("\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <h4 class=\"fw-bold mt-3 p-0\">我的自訂地點</h4>\r\n");
      out.write("                <!--customLocation btn start -->\r\n");
      out.write("                ");
      if (_jspx_meth_c_005fforEach_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                <!--customLocation btn end -->\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("      <!-- loc info start -->\r\n");
      out.write("\r\n");
      out.write("      <div class=\"col-3 locInfo-title\" id=\"mem-notes\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("          <ul class=\"nav nav-pills p-0\" role=\"tablist\">\r\n");
      out.write("            <li class=\"nav-item w-50\" role=\"presentation\">\r\n");
      out.write("              <button class=\"btn trip-btn w-100 active\" id=\"mbr-btn\" data-bs-toggle=\"pill\" data-bs-target=\"#mbr\"\r\n");
      out.write("                type=\"button\" role=\"tab\" aria-controls=\"mbr\" aria-selected=\"true\">\r\n");
      out.write("                <i class=\"bi bi-people-fill fa-2x\"></i>\r\n");
      out.write("                <p class=\"m-0 d-inline\">成員(5)</p>\r\n");
      out.write("              </button>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item w-50\" role=\"presentation\">\r\n");
      out.write("              <button class=\"btn trip-btn w-100\" id=\"note-btn\" data-bs-toggle=\"pill\" data-bs-target=\"#notes\"\r\n");
      out.write("                type=\"button\" role=\"tab\" aria-controls=\"notes\" aria-selected=\"false\">\r\n");
      out.write("                <i class=\"bi bi-stickies-fill fa-2x\"></i>\r\n");
      out.write("                <p class=\"m-0 d-inline\">筆記</p>\r\n");
      out.write("              </button>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("\r\n");
      out.write("          <!-- trip member start -->\r\n");
      out.write("          <div class=\"tab-content h-100 overflow-auto\">\r\n");
      out.write("            <div class=\"tab-pane fade show active p-3 overflow-auto\" id=\"mbr\" role=\"tabpanel\" aria-labelledby=\"mbr-tab\"\r\n");
      out.write("              style=\"height: calc(100vh - 66px - 65px);\">\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <h3 class=\"col-12 text-center text-truncate\">\r\n");
      out.write("                  活動名稱活動名稱活動名稱活動名稱活動名稱\r\n");
      out.write("                </h3>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <form action=\"\" method=\"post\">\r\n");
      out.write("                  <input class=\"col-8 newLoc-input\" type=\"text\" placeholder=\"請輸入好友帳號\">\r\n");
      out.write("                  <button class=\"btn trip-btn py-0 px-1\" type=\"submit\"><i\r\n");
      out.write("                      class=\"bi bi-person-plus-fill fa-2x\"></i></button>\r\n");
      out.write("                </form>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <h5 class=\"col-12 fw-bold\">群組成員</h5>\r\n");
      out.write("                <div class=\"col-12 my-2\">\r\n");
      out.write("                  <img src=\"./images/dog.jpeg\" alt=\"\" class=\"mbr-pic\">\r\n");
      out.write("                  <h5 class=\"d-inline align-middle\">成員名稱</h5>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <h5 class=\"col-12 fw-bold mt-2 mb-0\">邀請中(人數)</h5>\r\n");
      out.write("                <div class=\"col-12 my-2\">\r\n");
      out.write("                  <img src=\"./images/dog.jpeg\" alt=\"\" class=\"mbr-pic\">\r\n");
      out.write("                  <h5 class=\"d-inline align-middle\">成員名稱</h5>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- trip member end -->\r\n");
      out.write("\r\n");
      out.write("            <!-- trip notes start -->\r\n");
      out.write("            <div class=\"tab-pane fade\" id=\"notes\" role=\"tabpanel\" aria-labelledby=\"notes-tab\">\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"col m-2\">\r\n");
      out.write("                  <form action=\"\" method=\"post\">\r\n");
      out.write("                    <textarea name=\"\" id=\"note-input\" placeholder=\"旅程中，有些物品必定要帶的。可以寫在這邊，來提醒旅遊成員喔~\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tripVO.note}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("                    <button class=\"btn trip-btn col-12 border-dark\">儲存</button>\r\n");
      out.write("                  </form>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("          <!-- trip notes end -->\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- mbr group msg start -->\r\n");
      out.write("      <div class=\"col-3 p-2 pt-0\" id=\"mbr-chat\">\r\n");
      out.write("        <div class=\"row\" style=\"background-color: rgba(38, 112, 180, 0.6);\">\r\n");
      out.write("          <h5 class=\"col-6 text-truncate text-start fw-bold m-0 align-middle py-2\">活動名稱(人數)</h5>\r\n");
      out.write("          <button class=\"col-2 btn trip-btn\" id=\"notes-btn\"><i class=\"bi bi-stickies-fill\"></i></button>\r\n");
      out.write("          <button class=\"col-2 btn trip-btn\" id=\"mbrs-btn\"><i class=\"bi bi-gear-fill\"></i></button>\r\n");
      out.write("          <button class=\"col-2 btn trip-btn\" id=\"close-msg\"><i class=\"bi bi-dash\"></i></button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <hr class=\"m-0\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row\" id=\"msg-content\">\r\n");
      out.write("          <div class=\"col-12 m-2\">\r\n");
      out.write("            <img src=\"./images/dog.jpeg\" class=\"user-pic d-inline align-top\" alt=\"使用者\">\r\n");
      out.write("            <p class=\"trip-msg\">\r\n");
      out.write("              xxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX</p>\r\n");
      out.write("            <p class=\"d-inline align-bottom\" style=\"font-size: 10px;\">下午12:00</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-12 m-2\">\r\n");
      out.write("            <img src=\"./images/dog.jpeg\" class=\"user-pic d-inline align-top\" alt=\"使用者\">\r\n");
      out.write("            <p class=\"trip-msg\">\r\n");
      out.write("              XXXXXXXXXXXXXXXXX</p>\r\n");
      out.write("            <p class=\"d-inline align-bottom\" style=\"font-size: 10px;\">下午12:00</p>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"col-12 m-2 text-end\">\r\n");
      out.write("            <p class=\"d-inline align-bottom\" style=\"font-size: 10px;\">下午12:00</p>\r\n");
      out.write("            <p class=\"trip-msg\">\r\n");
      out.write("              xxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX</p>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"row\" style=\"background-color: aliceblue;\">\r\n");
      out.write("          <form action=\"\" method=\"post\">\r\n");
      out.write("            <input type=\"text\" id=\"msg-input\">\r\n");
      out.write("            <button type=\"submit\" class=\"btn trip-btn\"><i class=\"bi bi-send-fill\"></i></button>\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- mbr group msg end -->\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- mbr group msg icon -->\r\n");
      out.write("  <button class=\"btn\" id=\"mbrMsg-icon\"><i class=\"bi bi-chat-dots-fill fa-4x\"></i></button>\r\n");
      out.write("  <!-- mbr group msg icon end -->\r\n");
      out.write("  <a href=\"");
      out.print(request.getContextPath());
      out.write("/front-end/shareGroup/shareGroup.jsp?TRIP_NAME=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tripVO.tripName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&STARTDATE=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tripVO.startDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&ENDDATE=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tripVO.endDate}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"open-join\" target=\"_blank\">公開揪團</a>\r\n");
      out.write("  <button id=\"invite\" class=\"btn\">邀請好友</button>\r\n");
      out.write("\r\n");
      out.write("  <div id=\"map\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <script src=\"https://unpkg.com/leaflet@1.9.3/dist/leaflet.js\"\r\n");
      out.write("    integrity=\"sha256-WBkoXOwTeyKclOHuWtc+i2uENFpDZ9YPdf5Hf+D7ewM=\" crossorigin=\"\"></script>\r\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/front-end/js/tripPlan.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/front-end/js/map.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("    integrity=\"sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ\"\r\n");
      out.write("    crossorigin=\"anonymous\"></script>\r\n");
      out.write("  <script src=\"https://kit.fontawesome.com/616f19a0b0.js\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("  <script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/front-end/js/jquery.datetimepicker.full.js\"></script>\r\n");
      out.write("  <script src=\"");
      out.print(request.getContextPath() );
      out.write("/front-end/js/userTripAll.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /front-end/TripPlan/tripPlan.jsp(69,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tripVO.coverPic != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("            <img src=\"data:image/png;base64,");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Base64.getEncoder().encodeToString(tripVO.coverPic)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"w-100 h-100\">\r\n");
          out.write("          ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /front-end/TripPlan/tripPlan.jsp(72,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tripVO.coverPic == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("          	<img style=\"background-color: gray\" class=\"w-100 h-100\">\r\n");
          out.write("          ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /front-end/TripPlan/tripPlan.jsp(101,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("tripDetail");
      // /front-end/TripPlan/tripPlan.jsp(101,1) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${list}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("        <div class=\"row\">\r\n");
            out.write("          <a href=\"tripLoc.do?LOC_ID=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tripDetail.locId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&action=getOneLoc\" class=\"btn trip-btn col-12 d-flex align-items-center bg-cblue my-1\">\r\n");
            out.write("            <div class=\"col-3\">\r\n");
            out.write("              <img src=\"data:image/png;base64,");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Base64.getEncoder().encodeToString(LocationPicService().getLocPic(tripDetail.locId).get(0).getLocPic())}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_1));
            out.write("\" class=\"w-100\">\r\n");
            out.write("            </div>\r\n");
            out.write("            <div class=\"col-8 px-2 text-start\">\r\n");
            out.write("              <p class=\"m-1\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SimpleDateFormat(\"HH:mm\").format(tripDetail.arrivalTime)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
            out.write(' ');
            out.write('-');
            out.write(' ');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${SimpleDateFormat(\"HH:mm\").format(tripDetail.leaveTime)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
            out.write("</p>\r\n");
            out.write("              <p class=\"m-1 text-truncate\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${LocationService().getOneLoc(tripDetail.locId).getLocName()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_2));
            out.write("</p>\r\n");
            out.write("            </div>\r\n");
            out.write("          </a>\r\n");
            out.write("        </div>\r\n");
            out.write("	");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /front-end/TripPlan/getOne_LocInfo.jsp(46,9) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${locVO != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("            <div class=\"tab-pane fade show active\" id=\"locInfo\" role=\"tabpanel\" aria-labelledby=\"locInfo-tab\">\r\n");
          out.write("\r\n");
          out.write("              <div id=\"loc-pic\" class=\"carousel slide\" data-bs-ride=\"carousel\">\r\n");
          out.write("                <div class=\"carousel-indicators\">\r\n");
          out.write("                ");
          if (_jspx_meth_c_005fforEach_005f1(_jspx_th_c_005fif_005f2, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                </div>\r\n");
          out.write("                <div class=\"carousel-inner\">\r\n");
          out.write("                \r\n");
          out.write("                ");
          if (_jspx_meth_c_005fforEach_005f2(_jspx_th_c_005fif_005f2, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                  \r\n");
          out.write("                </div>\r\n");
          out.write("                <button class=\"carousel-control-prev\" type=\"button\" data-bs-target=\"#loc-pic\" data-bs-slide=\"prev\">\r\n");
          out.write("                  <span class=\"carousel-control-prev-icon\" aria-hidden=\"true\"></span>\r\n");
          out.write("                </button>\r\n");
          out.write("                <button class=\"carousel-control-next\" type=\"button\" data-bs-target=\"#loc-pic\" data-bs-slide=\"next\">\r\n");
          out.write("                  <span class=\"carousel-control-next-icon\" aria-hidden=\"true\"></span>\r\n");
          out.write("                </button>\r\n");
          out.write("              </div>\r\n");
          out.write("\r\n");
          out.write("              <div class=\"row my-3\">\r\n");
          out.write("                <p class=\"col-12 fs-5 text-center text-truncate\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${locVO.locName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</p>\r\n");
          out.write("                <p class=\"col-12 m-0 px-5 text-start\">Address:</p>\r\n");
          out.write("                <p class=\"col-12 m-0 fs-5 text-center text-truncate\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${locVO.locAddress}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</p>\r\n");
          out.write("                <p class=\"col-12 m-0 px-5 text-start\">Phone:</p>\r\n");
          out.write("                <p class=\"col-12 m-0 fs-5 text-center text-truncate\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${locVO.locPhone.length() == null? \"---\":locVO.locPhone}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</p>\r\n");
          out.write("              </div>\r\n");
          out.write("\r\n");
          out.write("              <div class=\"row justify-content-center\">\r\n");
          out.write("                <button class=\"col-8 btn trip-btn fw-bold border-dark\" data-bs-toggle=\"modal\"\r\n");
          out.write("                  data-bs-target=\"#exampleModal\">加入行程</button>\r\n");
          out.write("                <div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\"\r\n");
          out.write("                  aria-hidden=\"true\">\r\n");
          out.write("                  <div class=\"modal-dialog modal-dialog-centered\">\r\n");
          out.write("                    <div class=\"modal-content\">\r\n");
          out.write("                      <div class=\"modal-header\">\r\n");
          out.write("                        <h5 class=\"modal-title fw-bold\" id=\"exampleModalLabel\">加入行程</h5>\r\n");
          out.write("                        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
          out.write("                      </div>\r\n");
          out.write("                      <form action=\"tripDetail.do\" method=\"post\">\r\n");
          out.write("                        <div class=\"modal-body\">\r\n");
          out.write("                          <div class=\"text-center m-2\">\r\n");
          out.write("                            <label for=\"\">預計到達時間 : </label>\r\n");
          out.write("                            <input type=\"text\" name=\"arrivalTime\">\r\n");
          out.write("                          </div>\r\n");
          out.write("                          <div class=\"text-center m-2\">\r\n");
          out.write("                            <label for=\"\">預計離開時間 : </label>\r\n");
          out.write("                            <input type=\"text\" name=\"leaveTime\">\r\n");
          out.write("                          </div>\r\n");
          out.write("                          <div class=\"text-center m-2\">\r\n");
          out.write("                            <label for=\"\">預計停留時間 : </label>\r\n");
          out.write("                            <input type=\"text\" disabled>\r\n");
          out.write("                          </div>\r\n");
          out.write("\r\n");
          out.write("                        </div>\r\n");
          out.write("                        <input type=\"hidden\" name=\"action\" value=\"addTripLoc\">\r\n");
          out.write("                        <input type=\"hidden\" name=\"TRIP_ID\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tripVO.tripId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("                        <input type=\"hidden\" name=\"LOC_ID\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${locVO.locId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("                        <div class=\"modal-footer\">\r\n");
          out.write("                          <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">取消</button>\r\n");
          out.write("                          <button type=\"submit\" class=\"btn btn-primary\">確定</button>\r\n");
          out.write("                        </div>\r\n");
          out.write("                      </form>\r\n");
          out.write("                    </div>\r\n");
          out.write("                  </div>\r\n");
          out.write("                </div>\r\n");
          out.write("              </div>\r\n");
          out.write("            </div>\r\n");
          out.write("          <script>\r\n");
          out.write("      		$(document).ready(function(){\r\n");
          out.write("      			$('#loc-info').addClass('show');\r\n");
          out.write("      			$('#picControl-0').addClass('active');\r\n");
          out.write("      			$('#infoPic-0').addClass('active');\r\n");
          out.write("      		});\r\n");
          out.write("      	  </script>\r\n");
          out.write("      	");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
      // /front-end/TripPlan/getOne_LocInfo.jsp(51,16) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("locPic");
      // /front-end/TripPlan/getOne_LocInfo.jsp(51,16) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${locPicList}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /front-end/TripPlan/getOne_LocInfo.jsp(51,16) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVarStatus("num");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                  <button type=\"button\" data-bs-target=\"#loc-pic\" id=\"picControl-");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${num.index}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" data-bs-slide-to=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${num.index}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"></button>\r\n");
            out.write("                ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
      // /front-end/TripPlan/getOne_LocInfo.jsp(57,16) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("locPic");
      // /front-end/TripPlan/getOne_LocInfo.jsp(57,16) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${locPicList}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /front-end/TripPlan/getOne_LocInfo.jsp(57,16) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVarStatus("num");
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                  <div class=\"carousel-item\" id=\"infoPic-");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${num.index}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" style=\"height: 250px;\">\r\n");
            out.write("                    <img src=\"data:image/png;base64,");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Base64.getEncoder().encodeToString(locPic.locPic)}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"d-block w-100 h-100\">\r\n");
            out.write("                  </div>\r\n");
            out.write("                ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f3 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f3_reused = false;
    try {
      _jspx_th_c_005fforEach_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f3.setParent(null);
      // /front-end/TripPlan/getOne_LocInfo.jsp(146,16) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f3.setVar("locVO");
      // /front-end/TripPlan/getOne_LocInfo.jsp(146,16) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f3.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loclist}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int[] _jspx_push_body_count_c_005fforEach_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f3 = _jspx_th_c_005fforEach_005f3.doStartTag();
        if (_jspx_eval_c_005fforEach_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                <a href=\"tripLoc.do?LOC_ID=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${locVO.locId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&action=getOneLoc\" class=\"btn trip-btn col-12 d-flex align-items-center bg-cblue my-2\">\r\n");
            out.write("                  <div class=\"col-3\">\r\n");
            out.write("                    <img src=\"data:image/png;base64,");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Base64.getEncoder().encodeToString(LocationPicService().getLocPic(locVO.locId).get(0).getLocPic())}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_1));
            out.write("\" class=\"w-100\">\r\n");
            out.write("                  </div>\r\n");
            out.write("                  <div class=\"col-8 px-2\">\r\n");
            out.write("                    <p class=\"text-start text-truncate m-1\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${locVO.locName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("                    <p class=\"text-start text-truncate m-1\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${locVO.locAddress}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("                  </div>\r\n");
            out.write("                </a>\r\n");
            out.write("                ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f3.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f3.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f3);
      _jspx_th_c_005fforEach_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f3_reused);
    }
    return false;
  }
}
